#T1: install mysql server
#T2: start the mysql service
#T3: Check if root user is created or not
#T4: Install dependencies


- name: mysql configuration
  hosts: mysql
  become: yes
  vars:
    mysql_password: "ExpenseApp@1"
    mysql_host: "mysql.vijaydevops.store"
  tasks:
  - name: install python lib PyMySQL
    ansible.builtin.pip:
      name:
      - PyMySQL
  - name: install MySQL Server
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: start mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: Connecting to mysql server  
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{mysql_password}}"
      login_host: "{{mysql_host}}"
    ignore_errors: true  
    register: mysql_info
  - name: print the mysql_info
    ansible.builtin.debug:
      msg: "{{mysql_info}}"
  