- name: remove existing app location
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: absent
  ignore_errors: true  #if location itself is not there we have to continue to next step

- name: create app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

- name: "download the {{ component }} code"
  ansible.builtin.unarchive:
    src: "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
    dest: "{{ app_location }}"
    remote_src: yes