- name: find whether given number is more than 10 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: Please enter the number
    private: false # not confidential
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id expense
    register: USER #here USER is a variable that gets output from above command
    ignore_errors: true
    
  
  - name: check whether number is greater than 10
    ansible.builtin.debug:
      msg: "{{my_number}} is greater than 10"
    when: my_number | int >= 10
  