- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-04e700eb774de69c5 # replace with your subnet id
    sg_id: "sg-0bc7f605c01cc2ed2" # replace with your security group id
    ami_id: "ami-09c813fb71547fc4f" # replace with your image id
    instances:
    - mysql
    - backend
    - frontend
    zone: vijaydevops.store #replace your zone
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
  - name: display ec2 instance
    ansible.builtin.debug:
      msg: "{{ec2_instances}}"