#Requirements
# 3 instances and 3 records
# to avoid any file changes when there is a change in ip address
# public ip and private ip address from instances based on it we will create records.
#mysql.vijaydevops.store - private ip of sql
#backend.vijaydevops.store - private ip of backend
#frontend.vijaydevops.store - private ip of frontend
#vijaydevops.store - public ip of frontend

- name: create ec2 and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-04e700eb774de69c5 # replace with your subnet id
    sg_id: "sg-0bc7f605c01cc2ed2" # replace with your security group id
    ami_id: "ami-09c813fb71547fc4f" # replace with your image id
    instances:
    - mysql
    - backend
    - frontend
    zone: vijaydevops.store #replace your zone
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances
  - name: display ec2 instance
    ansible.builtin.debug:
      msg: "{{ec2_instances}}"
  - name: create r53 private records  
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item }}.{{ zone }}" #mysql.vijaydevops.store
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
  - name: create r53 public record for frontend 
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}" #vijaydevops.store
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true
    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend"